accounts/urls.py
from django.urls import path
from .views import login_view

app_name = 'accounts'

urlpatterns = [
    path('', login_view, name='login'),
]

main/urls.py
from django.urls import path
from .views import (
    contacts_view, about_view, main_view,weather_view,
)

app_name='main'

urlpatterns = [
    path('contacts/', contacts_view,name='contacts'),
    path('about/', about_view,name='about'),
    path('', main_view,name='index'),
    path('weather/', weather_view, name='weather'),



]

#img = urllib.request.urlopen(f"http://openweathermap.org/img/w/{icon}.png")

products/urls.py
from django.urls import path
from .views import (
    list_view, detail_view)

app_name = 'products'

urlpatterns = [
    path('<int:pk>/', detail_view, name="detail"),
    path('', list_view, name='index'),
]

server/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('accounts/',include('accounts.urls')),
    path('', include('main.urls')),

]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class Accountuser(AbstractUser):
    avatar=models.ForeignKey(
        'images.image',
        on_delete=models.PROTECT,
        null=True,
        blank=True,
    )
    phone=models.CharField(
        max_length=11,
        null=True,
        blank=True,
    )

    def __str__(self):
        return self.username

# Create your models here.

images/models.py
from django.db import models

# Create your models here.
class Image(models.Model):
    name=models.CharField(
        max_length=150,

    )
    value=models.ImageField(
        upload_to='images'
    )

    @property
    def url(self):
        return  self.value.url

    def __str__(self):
        return self.name

products/models.py
from django.db import models
from .utills import get_default_category


class Category(models.Model):
    name = models.CharField(
        max_length=250,
    )
    description = models.TextField(
        null=True,
        blank=True,
    )



    modified = models.DateTimeField(
        auto_now=True,

    )

    created = models.DateTimeField(
        auto_now_add=True,

    )

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=250)

    description = models.TextField(
        null=True,
        blank=True
    )

    image=models.ForeignKey(
        'images.image',
        on_delete=models.PROTECT,
        null=True,
        blank=True,
    )


    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        default=get_default_category
        #default=1

    )

    cost = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        default=0,
    )

    modified = models.DateTimeField(
        auto_now=True,

    )

    created = models.DateTimeField(
        auto_now_add=True,

    )

    short_description = models.TextField()

    def __str__(self):
        return self.name

utillity/models.py
from django.db import models

# Create your models here.
class DateTimeManager (models.Model):

    modified = models.DateTimeField(
        auto_now=True,

    )

    created = models.DateTimeField(
        auto_now_add=True,

    )

class Meta:
    abstract=True

accounts/forms.py
from django import forms

class LoginForm(forms.Form):
    username=forms.CharField(
        label='Логин',
        max_length=150,
        widget=forms.widgets.TextInput(
            attrs={
                'class': 'field field-password'
            }
        )
    )
    password = forms.CharField(
        label='Пароль',
        max_length=72,
        widget=forms.widgets.PasswordInput(
            attrs={
                'class':'field field-password'
            }
        )

    )

main/forms.py
from django import forms

Time = [["00:00:00", "00:00:00"],
        ["03:00:00", "03:00:00"],
        ["06:00:00", "06:00:00"],
        ["09:00:00", "09:00:00"],
        ["12:00:00", "12:00:00"],
        ["15:00:00", "15:00:00"],
        ["18:00:00", "18:00:00"],
        ["21:00:00", "21:00:00"],
        ["00:00:00", "00:00:00"],

        ]


class TimeForm(forms.Form):
    from_ = forms.ChoiceField(choices=Time)
    to_ = forms.ChoiceField(choices=Time)

accounts/views.py
from django.shortcuts import render
from .forms import LoginForm
# Create your views here.
def login_view(request):
    form=LoginForm()
    return render(
        request,
        'accounts/login.html',
        {
            'form':form
        }
    )

images/views.py
from django.shortcuts import render

# Create your views here.

main/views.py
from django.template import Template, Context
from django.template.loader import get_template, render_to_string
from django.shortcuts import render
from django.http import HttpResponse
from main.weather import Weather
from main.forms import TimeForm


obj=Weather()
obj.create_wiew_of_weather()

#def state_(self):
 #   """ Return the text of the state rather than an integer """
  #  return self.STATE[self.state]


def main_view(request):
    # template = Template(
    #     'Hello {{ name }}'
    # )
    # context = Context({
    #     'name': 'Anton'
    # })
    # response_string = template.render(context)

    # template = get_template('main/index.html')

    # context = {
    #     'title': 'This is a main page',
    #     'subtitle': 'First django page',
    #     'username': request.user,
    # }

    # response_string = template.render(context)

    response_string = render_to_string(
        'main/index.html',
        {
            'title': 'This is a main page',
            'subtitle': 'First django page',
            'username': request.user,
            'is_active': True
        }
    )

    # return render(request, 'main/index.html')
    return HttpResponse(response_string)


def contacts_view(request):
    return render(
        request,
        'main/contacts.html',
        {
            'contacts': [
                'Почта : taytds10@gmail.com',

            ]
        }
    )


def about_view(request):
    return render(
        request,
        'main/about.html',
        {
            'text': 'Проектируем...'
        }
    )


def weather_view(request):
    form = TimeForm(request.GET or None)
    if form.is_valid():
        from_= form.cleaned_data['from_']
        to_= form.cleaned_data['to_']
        obj.change_time(from_,to_)
        obj.create_wiew_of_weather()
    if 'refresh' in request.GET:
        obj.refresh_weather()

    else:
        pass

    return render(
        request,
        'main/weather.html',
        {
            'погода': obj.list_of_weathers,

            'form':form,

        },

    )

products/views.py
import json
from django.shortcuts import (
    render, get_list_or_404, get_object_or_404
)
from .models import Product


def list_view(request):
    # with open('data.json', 'r') as file:
    #     context = json.load(file)
    # return render(
    #     request,
    #     'products/list.html',
    #     {
    #         'products': context.get('products') or []
    #     }
    # )
    return render(request,'products/list.html',
                  {
                      'products':Product.objects.all()
                  })

def detail_view(request, pk):
    # with open('data.json', 'r') as file:
    #     context = json.load(file)
    #
    # products = context.get('products')
    #
    # return render(
    #     request,
    #     'products/detail.html',
    #     {
    #         'object': products[pk] if len(products) > pk else ''
    #     }
    # )

    return render(request, 'products/detail.html',
                  {
                      'object':  get_object_or_404(Product, id=pk)
                  })

utillity/views.py
from django.shortcuts import render

# Create your views here.

accounts/templates/accounts/login.html
{% extends 'master.html' %}

{% block page_content %}
    <form method="POST" action="{% url 'accounts:login' %}">
        {% csrf_token %}
        {% for field in form %}
            <div class="field.group">
                <label for="{{ field.name }}">{{ field.label }}</label>
                {{ field }}
            </div>
        {% endfor %}
    <input type="submit">
    </form>
{% endblock %}

main/templates/main/about.html
{% extends 'master.html' %}
{% load static %}
{% block page_title %}
О проекте
{% endblock %}
{% block page_content %}
<style>
    html { height: 100%; }
    body { background: url(/static/img/back.png) no-repeat;
         background-size: cover;
  }
</style>
<h1 id="h1a" >Проект джанго</h1>
<p id="ta">Здесь, далее будет вестись разработка веб-приложения на платформе джанго.
    Надеюсь все получится.Настраиваю гит.
</p>
    <p id="ab">
        {{ text }}
    </p>
{% endblock %}

main/templates/main/contacts.html
{% extends 'master.html' %}
{% load static %}
{% block page_title %}
Контакты
{% endblock %}
{% block page_content %}
<h1 id="c3" >Контакты</h1>

<div class="list">
    <ul>
        {% for itm in contacts %}
        <li  >{{ itm }}</li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

main/templates/main/index.html
{% extends 'master.html' %}
{% load static %}
{% block page_title %}
    Главная страница

{% endblock %}

{% block page_content %}


    <h1 id="h1m"> Это главная страница </h1>
    <h2 id="h2m">Скоро здесь будут плитки...</h2>


    <style>
        html {
            height: 100%;
        }

        body {
            background: url({% static 'img/main.jpg' %}) no-repeat;
            background-size: cover;
        }
    </style>
    {% if is_active %}
        <h3>
            {{ username }}
        </h3>
    {% else %}
        <p id="u">
            User is not active
        </p>

    {% endif %}
{% endblock %}

main/templates/main/weather.html
{% extends 'master.html' %}
{% load static %}
{% block page_title %}
    Погода
{% endblock %}
{% block page_content %}
    <h1 id="weather">Погода в Москве </h1>


    <div class="grid">
        <div class="choose">
            <p>Выбор времени </p>
            <form action="" method="get" name="send">

                От: {{ form.from_ }} до: {{ form.to_ }}

                <p><input type="submit" value="Отправить"></p>

                <p><input type="submit" value="Обновить" name="refresh"></p>

            </form>

        </div>
        {% for itm in погода %}

            <div class="col-1-3">
                <p><img id="logo" src="http://openweathermap.org/img/w/{{ itm.logo }}.png"></p>
                <p> {{ itm.data_time }}  </p>
                <p> Т мин: {{ itm.Tmin }} °C &nbsp;&nbsp; Т макс: {{ itm.Tmax }} °C </p>
                <p> Ветер: {{ itm.Wind }} м/c </p>
            </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

products/templates/products/detail.html
{% extends 'master.html' %}
{% load static %}
{% block page_title %}
    Продукты
{% endblock %}

{% block page_content %}

    {% if object %}
        {% if object.name == "kiwi" %}
            <h1 id="hk">Киви</h1>

            <p id="p3"><img id="kiwi" src="{% static 'img/kiwi.jpg' %}" alt="Киви" class="leftpic">{{object.short_description}}</p>
            <h3 id="h3k">История селекции киви</h3>


            <p id="p4"><img id="kiwi-a" src="/static/img/adler.jpg" alt="Киви в адлере" width="700" height="500"
                            class="rightpic">{{ object.description }} </p>


        {% endif %}

        {% if object.name == "banana" %}
            <h1 id="hk">Банан</h1>
            <p id="p3"><img id="banan" src="{% static 'img/banan_v.jpg' %}" alt="Банан во въетнаме"
                            class="leftpic">{{ object.short_description }}</p>
            <h3 id="h3k">Применение </h3>
            <p id="p4"><img id="banans" src="{% static 'img/banans.JPG' %}" alt="Киви в адлере"
                            class="rightpic">{{ object.description }}</p>
        {% endif %}
    {% else %}
        Product does not exists
    {% endif %}

{% endblock %}

products/templates/products/list.html
{% extends 'master.html' %}
{% load static %}
{% block page_title %}
Products list page
{% endblock %}

{% block page_content %}
<ul>
    {% for itm in products %}
    <li>
     <a href="{% url 'products:detail' pk=itm.id %}">{{ itm.name }}</a>
    </li>
    {% endfor %}
</ul>
{% endblock %}

server/templates/master.html
{% load static %}
<!DOCTYPE html>

<html>

<head>
    <meta charset="utf-8" />
    <link href="https://fonts.googleapis.com/css?family=Didact+Gothic" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">

    <title>
        {% block page_title %}{% endblock %}
    </title>
</head>

<body>
    <section>
        {% block page_content %}{% endblock %}
        <ul id="contm">
    <li>
        <a style="color:rgba(59, 157, 29, 0.98)" href="{% url 'main:index' %}">Главная </a>
        <a style="color:rgba(59, 157, 29, 0.98)" href="{% url 'main:contacts' %}">Контакты </a>
        <a style="color:rgba(59, 157, 29, 0.98)" href="{% url 'main:about' %}"> О проекте </a>
        <a style="color:rgba(59, 157, 29, 0.98)" href="{% url 'products:index' %}"> Продукты </a>
        <a style="color:rgba(59, 157, 29, 0.98)" href="{% url 'main:weather' %}"> Погода </a>

    </li>
        </ul>
    </section>


</body>

</html>